### ISSUE TITLE
Create blocking mode for M::P::OAuth2

### ISSUE THREAD

**Issue by akarelas** [marcusramberg/Mojolicious-Plugin-OAuth2#42]
I am going to try to create a pull-request for this module, which will allow it to work in blocking mode as well. I'm creating this issue so we can discuss the various difficulties and problems I encounter.

**Comment by akarelas** [comment]
Most of the work will take place in the ```_process_response_code``` method.

```pop``` (the method's first line) should only occur if the last parameter is a subroutine or the result of ```$delay->begin```. I wonder what's a good way to check whether a variable is the result of ```$delay->begin```, is it ```ref $var eq 'CODE'``` ? please advise.

Then, if $cb is false, $blocking should become true, and the entire ```return``` statement should be bypassed, in favor of one that does the same things in a blocking fashion.

Finally tests and documentation must be added for the blocking mode. I can't imagine yet how blocking mode can be tested, since, if it's blocking, then the OAuth server won't have a chance to run. Perhaps we should run two separate processes somehow?

**Comment by akarelas** [comment]
```_process_response_code``` could return a hashref, containing the ```$data```, the access token, and any errors. That's how the route handler will get the access token. Another way could be for ```_process_response_code``` to return a list of three values (access token, data, and error). Is there a preference?

**Comment by jhthorsen** [comment]
Please explain why you want the blocking API. I can't see any case where that is beneficial.

**Comment by akarelas** [comment]
I want the blocking API, because my entire site is blocking. Every web request happens in a mysql transaction, and I use an ORM library, so it's not easy, if even possible, to do my own custom "rollback or commit" at the end of the web request depending on whether an error has occurred. What say you now?

**Comment by jhthorsen** [comment]
It sounds like a bad ORM if you can't have transactions in a non-blocking environment. Anyhow... We used to support blocking mode, so I'm not against it.

To answer your questions:

* Good way to check for blocking/non-blocking.
```my $cb = ref $_[-1] eq 'CODE' ? pop : undef;```

* What about return values?
Both the blocking and non-blocking should have the same "return" value. That means the return value from the blocking method have to match the arguments passed into the callback in blocking mode. The exception to this is that the method should die on an error. Something like this:
```
return $self if $non_blocking_mode;
die $err if $err;
return $data;
```

* Tests
It's no problem. It should just work in the same process because of https://github.com/marcusramberg/Mojolicious-Plugin-OAuth2/blob/master/lib/Mojolicious/Plugin/OAuth2.pm#L241

**Comment by jhthorsen** [comment]
@akarelas: Have you had any time to look at my reply?

**Comment by akarelas** [comment]
No, I'll look at it this evening. Thanks a lot.

**Comment by akarelas** [comment]
From what I understand, the blocking example usage in the POD documentation should be something like:

```perl
my $data = eval { $self->oauth2->get_token('facebook', $config) };
```

After that must follow a line that checks whether this is the first or the second time get_token is running. The solution I can think of is having get_token return the string 'redirect' the first time it runs, when in blocking mode. Then the next line in the example would be:

```perl
if (($data // '') eq 'redirect') { return; }
if (my $err = $@) {
    # handle error
}
# handle $data->{access_token}
```

Is that good enough? Any better ideas?

**Comment by jhthorsen** [comment]
I don't want "eval" in the synopsis. Just a mention that it will die on error. About the return value... How about:
* ref $data eq HASH when redirected back
* undef when redirected to OAuth2 provider
* die on error

It would allow code like this:
```
if (my $err = $c->param("error")) {
  # do stuff with error from OAuth2 provider
} elsif (my $data = $self->oauth2->get_token("facebook")) {
  # do stuff with $data->{access_token};
} else {
  # already redirected by OAuth2 plugin
}
```

**Comment by akarelas** [comment]
I issued a pull request on #44

**Comment by akarelas** [comment]
I just realized I neglected to edit ```sub _process_response_error { ... }```, which I should have edited.

I wonder what behaviour this method should have in blocking apps. I have 2 ideas, none of which I find particularly clever:

 1. Let it return a ```$data``` that contains an ```error``` key, but no ```access_token```, or...
 2. ```die $error```

Do you like one of these? Do you have another preference? Give me some time to think which one is better.

**Comment by jhthorsen** [comment]
Always die on error.

**Comment by akarelas** [comment]
Done.

**Comment by akarelas** [comment]
Pull request created, merged, and published on CPAN. Closing.
