### ISSUE TITLE
_process_response_error forwards error_description param instead of the error param

### ISSUE THREAD

**Issue by akarelas** [marcusramberg/Mojolicious-Plugin-OAuth2#43]
The problem with that is that the callback has no way of telling whether the user has refused to authenticate. I think such a check is better done with error code rather than error description.

**Comment by jhthorsen** [comment]
@akarelas: How about $c->param("error") ?

**Comment by akarelas** [comment]
Correct. If you're happy with using $c->param("error"), you may close this issue.

**Comment by jhthorsen** [comment]
What do you say @marcusramberg ?

**Comment by marcusramberg** [comment]
I am a happy camper
