### ISSUE TITLE
little optim and additional helper

### ISSUE THREAD

**Issue by mche** [marcusramberg/Mojolicious-Plugin-OAuth2#49]
HI Jan!
---

I have prepeare [patch](https://github.com/marcusramberg/Mojolicious-Plugin-OAuth2/compare/master...mche:master) where optim only.

And also new helper is convenient to have process any tx of API;

**Comment by jhthorsen** [comment]
I like the patch in general. A couple of questions:

* When do you need the oauth2.process_tx helper?
* Why didn't you just open a PR?

**Comment by mche** [comment]
> When do you need the oauth2.process_tx helper?

Okay, after the getting **access_token** I need the profile of external user and I process tx of request profile.

> Why didn't you just open a PR?

Okay, you did agree with me and I will open PR )
