### ISSUE TITLE
Default authorize_url and token_url for Google OpenID isn't fresh 

### ISSUE THREAD

**Issue by pavelsr** [marcusramberg/Mojolicious-Plugin-OAuth2#52]
Now it's:

```perl
google => {
      authorize_url => "https://accounts.google.com/o/oauth2/auth?response_type=code",
      token_url     => "https://accounts.google.com/o/oauth2/token",
    },
```

Actual are:

```
google => {
      authorize_url => "https://accounts.google.com/o/oauth2/v2/auth?response_type=code",
      token_url     => "https://www.googleapis.com/oauth2/v4/token",
    },
```

I think it's better to get this urls from [Discovery document](https://developers.google.com/identity/protocols/OpenIDConnect#discovery) and hardcode only one link: https://accounts.google.com/.well-known/openid-configuration

**Comment by marcusramberg** [comment]
I've updated the google endpoints, but would accept a pull request to automatically fetch them from .well-known.
