### ISSUE TITLE
test failures on FreeBSD-11.1 against perl-5.29.2

### ISSUE THREAD

**Issue by jkeenan** [marcusramberg/Mojolicious-Plugin-OAuth2#53]
Today I attempted to install this distribution against perl-5.29.2 on FreeBSD-11.1 using ```cpanm``` as the installer.  I experienced numerous test failures.  Please see attachment.

Thank you very much.
Jim Keenan
[JHTHORSEN.Mojolicious-Plugin-OAuth2-1.53.log.json.txt](https://github.com/marcusramberg/Mojolicious-Plugin-OAuth2/files/2307811/JHTHORSEN.Mojolicious-Plugin-OAuth2-1.53.log.json.txt)

**Comment by jhthorsen** [comment]
This should be fixed in "master" now. Going to release version 1.54 to CPAN within the next hour.

* f160318e810fb5cb21ba0c6931a5ecbd1fb3b97f
* 8cb82d750387d1e29f3eaac662ad19d40e543b02

**Comment by jkeenan** [comment]
Confirmed.
```
$ ./bin/perl -Ilib -v | head -2 | tail -1
This is perl 5, version 29, subversion 3 (v5.29.3 (v5.29.2-38-g0c6023b1f6)) built for amd64-freebsd-thread-multi

$ ./bin/cpanm Mojolicious::Plugin::OAuth2 
--> Working on Mojolicious::Plugin::OAuth2
Fetching http://www.cpan.org/authors/id/J/JH/JHTHORSEN/Mojolicious-Plugin-OAuth2-1.54.tar.gz ... OK
Configuring Mojolicious-Plugin-OAuth2-1.54 ... OK
==> Found dependencies: IO::Socket::SSL, Mojolicious
...
Building and testing Mojolicious-Plugin-OAuth2-1.54 ... OK
Successfully installed Mojolicious-Plugin-OAuth2-1.54
5 distributions installed
```
Thanks for your investigation.
