### ISSUE TITLE
Manual unclear about oauth2.jwt_decode

### ISSUE THREAD

**Issue by daleif** [marcusramberg/Mojolicious-Plugin-OAuth2#68]
About `oauth2.jwt_decode` the manual says

```
$claims = $c->oauth2->jwt_decode($provider, sub { my $jwt = shift; ... });
$claims = $c->oauth2->jwt_decode($provider);
```
> When [Mojolicious::Plugin::OAuth2](https://metacpan.org/pod/Mojolicious::Plugin::OAuth2) is being used in OpenID Connect mode 
this helper allows you to decode the response data encoded with the JWKS discovered from well_known_url configuration.

In the sources we have 

```
sub _jwt_decode {
  my $peek = ref $_[-1] eq 'CODE' && pop;
  my ($self, $c, $args) = @_;
  croak 'Provider does not have "jwt" defined.' unless my $jwt = $self->providers->{$args->{provider}}{jwt};
  return $jwt->decode($args->{data}, $peek);
}
```
Thus it is looking at data from the input. But there is no `data` being set anywhere.

Aren't we suppose to use it something like this

```
$claims = $c->oauth2->jwt_decode($provider, data => $provider_res->{id_token});
```

At least then I got the claims I was expecting.

**Comment by jhthorsen** [comment]
Yes, you are right - This is a bug in the documentation. The test agrees with you:

https://github.com/marcusramberg/Mojolicious-Plugin-OAuth2/blob/3c7e34d08cd30f650b3b3a68b23e662d217ba7d4/t/openid-connect.t#L35

Do you have time to open a PR to fix the documentation?

**Comment by daleif** [comment]
I think I managed to provide a proper pull request.

**Comment by daleif** [comment]
Do note that this information is also listed in the README for this repo. Not use if it is somehow generated from the POD at release time.
